mkdir projects
cd projects
mkdir personal_website
cd personal_website
touch index.html 
cd ..
mkdir tic_tac_toe 
cd tic_tac_toe
touch tic_tac_toe.js 
cd ..
mkdir hello
cd hello 
touch hello1.js 
touch hello2.js